### ISSUE TITLE
Trouble to build libxdo - encodings ?

### ISSUE THREAD

**Issue by EmmanuelDUMAS** [rshk/python-libxdo#19]
Hello

I Have try to install libxdo in a chroot from a Debian 7.
I use this way : 
```
(debian)edumas@xxx:xxx/libxdo$ tar zxf python-libxdo-0.1.2a1.tar.gz 
(debian)edumas@xxx:xxx/libxdo$ cd python-libxdo-0.1.2a1
(debian)edumas@xxx:xxx/libxdo/python-libxdo-0.1.2a1$ python3 ./setup.py build
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    longdesc = fp.read()
  File "/xxx/python/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1718: ordinal not in range(128)
(debian)edumas@xxx:xxx/libxdo/python-libxdo-0.1.2a1$ 

```

I also install other python module by this way (untar, setup build, setup install). By example module six is install like this without trouble.
I edit by hand file README.rst and MANIFEST.in by remoev any non ascii character, and now I can install libxdo.

Best regard
Emmanuel

**Comment by dustinfast** [comment]
I am experiencing this issue as well, when attempting to install with `pip install python-libxdo`. I'm on Ubuntu 18.04 using python3.6.
